apiVersion: apps/v1
kind: Deployment
metadata:
  name: pharmacy
  labels:
    app: pharmacy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pharmacy
  template:
    metadata:
      labels:
        app: pharmacy
    spec:
      containers:
      - name: pharmacy
        image: vishnuvamsithyejju/pharmacy:v3
        ports:
        - containerPort: 8085